// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bsyxoyguoaxradluustd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzeXhveWd1b2F4cmFkbHV1c3RkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2ODQ5ODIsImV4cCI6MjA2NzI2MDk4Mn0.ryCm013CniTfG2GK7ZX-zAoFOqKVvxzHvi_w9_CNhnA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});